TWITTER_KEY: 'i60kKMg8TmviwcowX1ylg0qfX' 
TWITTER_SECRET: 'cwPlytnJtFX99tgYw8cGb6zaaUosS9fAFUSUdiWteZdQ881ul4'
TOKEN: "531892136-9E3UGdCzWFUQcAQxAAD7HcMhypGElU5fF0roYpGP"
TOKEN_SECRET: "d3u9saVhYo4fKbYCCIjpctN8J46Bjd0E2eRR4Aine7yS6"